# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# push:
#   branches: 
#   - master 

name: 抖音火山版

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 0-12 * * *'
  watch:
     types: started
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【小乐】'
        run: |
          node hotsoon.js
        env:
          HOTSOONSIGNHEADER: ${{ secrets. HOTSOONSIGNHEADER }}
          HOTSOONSIGNKEY: ${{ secrets. HOTSOONSIGNKEY }}
          HOTSOONADHEADER: ${{ secrets. HOTSOONADHEADER }}
          HOTSOONADKEY: ${{ secrets. HOTSOONADKEY }}
          HOTSOONREADHEADER: ${{ secrets. HOTSOONREADHEADER }}
          HOTSOONREADKEY: ${{ secrets. HOTSOONREADKEY }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
